Name: Run install deps
runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v2
        
        - name: "Install Node"
          uses: actions/setup-node@v2
          with:
              node-version: "20.x"

        - name: "Install Deps"
          run: npm ci
          shell: bash

