Name: Run unit test
Description: "Just run unit tests. (TODO: parallels them)"
runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v2
        
        - name: "Run unit test with coverage"
          run: npm run test:unit
          shell: bash

        - name: "Report Coverage"
          if: ${{ github.ref != 'refs/heads/main' }}
          uses: davelosert/vitest-coverage-report-action@v2
