Name: Run unit test
Description: "Just run unit tests. (TODO: parallels them)"
runs:
    using: "composite"
    steps:
        - name: Use Node
          uses: actions/checkout@v2
        - name: "Install Node"
          uses: actions/setup-node@v2
          with:
              node-version: "20.x"
        - name: "Install Deps"
          run: npm ci
        - name: "Run unit test with coverage"
          run: npm run test:coverage
        - name: "Report Coverage"
          if: always() # Also generate the report if tests are failing
          uses: davelosert/vitest-coverage-report-action@v2
