Name: Run unit test
Description: "Just run unit tests. (TODO: parallels them)"
runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v2

        - name: "Install Node"
          uses: actions/setup-node@v2
          with:
              node-version: "20.x"

        - name: "Install Deps"
          run: npm ci
          shell: bash

        - name: "Run unit test with coverage"
          run: npm run test:coverage
          shell: bash

        - name: "Report Coverage"
          if: ${{ github.ref != 'refs/heads/main' }}
          uses: davelosert/vitest-coverage-report-action@v2
