Name: Run unit test
Description: "Just run unit tests. (TODO: parallels them)"
runs:
    using: "composite"
    steps:
        - name: "Run unit test"
          run: npm run test:unit -- --run
          shell: bash
