name: Main branch health check

on:
    push:
        branches:
            - "main"

jobs:
    unit-test:
        name: Run unit test
        runs-on: ubuntu-latest

        steps:
            - name: Run npm install
              uses: ./.github/actions/install-deps

            - name: Run unit test
              uses: ./.github/actions/unit-tests-chunks
