name: Main branch health check

on:
    push:
        branches:
            - "main"

jobs:
    unit-test:
        name: Run unit test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            
            - name: Run npm install
              uses: ./.github/actions/install-deps
              
            - name: Run unit test
              uses: ./.github/actions/unit-tests-chunks
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                slug: wi-untitled/github-exts
