name: "Run vitest with coverage report"
on:
    pull_request:

jobs:
    unit-tests:
        name: Run unit test
        runs-on: ubuntu-latest

        permissions:
            # Required to checkout the code
            contents: read
            # Required to put a comment into the pull-request
            pull-requests: write

        steps:
            - name: Checkout the commit
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Run unit test
              uses: ./.github/actions/unit-tests-coverage-chunks
