name: "Semantic Release"

on:
    push:
        branches:
            - "main"

jobs:
    release:
        name: Run release
        runs-on: ubuntu-latest

        permissions:
            contents: write
            packages: write

        steps:
            - uses: actions/checkout@v2
            
            - name: Run npm install
              uses: ./.github/actions/install-deps

            - name: "Build release"
              run: |
                npm run build:prod:release
            
            - name: "Zip dist directory"
              run: |
                zip -r dist.zip dist
            
            - name: "Run semantic release"
              run: |
                npx semantic-release --debug 

              env:
                NODE_AUTH_TOKEN: ${{secrets.SEMANTIC_RELEASE}}
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            

            
